on: 
  issue_comment:
    types:
      - created
name: Create Fork
jobs:
  create_fork:
    runs-on: ubuntu-latest
    environment: 
      name: Commands
      url: https://github.com
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.TOKEN }}
          command: fork
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: none
      - id: is_member
        uses: TheModdingInquisition/actions-team-membership@v1.0
        with:
          team: 'moddedjanitors'
          token: ${{ secrets.TOKEN }}
          comment: '@${{ github.actor }}, you need to be a ModdedJanitor in order to use this command.'
      - id: fork
        uses: TheModdingInquisition/actions-fork-repo@7f8fb9373abeed136ebf48fed9cc6d1911c259e6
        with:
          token: ${{ secrets.TOKEN }}
          organization: 'TheModdingInquisition'
          repo: ${{ steps.command.outputs.command-arguments }}
      - name: Create commit comment
        uses: ben-z/actions-comment-on-issue@1.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          message: '@${{ github.actor }}, a fork has been created at ${{ steps.fork.outputs.fork_url }}.'
